sudo: required
language: python
python:
- '3.6'
services:
- docker
script:
- "./bin/ci"
deploy:
- provider: pypi
  user: dev-im
  edge:
    source: ssbarnea/dpl
    branch: master
  password:
    secure: hhjn47GalCnADFUsLerOZALSHISeJbXyZ3N2UzChGsO3y3mERY7TD5eGFgXSkr+KlOq3Z96Im+N2f4TviRo9F87i0Z1jYAIIURDYFTJ90UQUugdyY5hjuPDDUYbEZbkcZVroW3Uq9dUpe4KcAnVFZmwIT0DEUTEgdyNzgkxMNBEobu/ZAu2tkWHu6PTWaJcpp+jII3vpay1o3HJbGdrbX9DLyC9ODHG7XJuePddQmDLuOTKOfnNxqo1tBkaw3a49bW2G1JWYpfof7l8AMaeCikRownAd0NrolDkRc19VfflvSe4w1FMYRGnZy1IJRo16olQEQiyDp8vBbAFe0xq6yncUsf12wXyRGFQqDgJXJImm0lg3oj8/4ag+ZxR8XvxGEgb+IWuqy+CD9bAVBbKRWQKeCgg2PQjTl7INoDIAaJ8f/Z65fhSB3uPZ1FlE8pBnNSFF0Lma2HGp1fIFM+jEH+WLbZKrUvYTXYvbfTUMwY41+u6Q+PEEkhqvNslOFTn2TZXwJSk0Eyq/FfhGS4jw5Bs/ngBybVSoB4ypHClo/dJcAVCl2KDx7Pc+GI1ZxNE1D6sJnOS4E6jJJdZYC9s/UQacHvTke+G3dXii9Y9BzEd508irw2DC0s+uJnSGzUm57tWHEbNAn+noZ0dhzLwCl7Jb6Uqe5sZDHK5/CqUcZeE=
  on:
    tags: true
- provider: script
  script: bash docker_push
  on:
    tags: true
notifications:
  slack:
    secure: dZRSuoImcjxOKrsMDhVJo2CfbkVwp77P9tlOLmRhbSVBytdcMCPx39pZHKM87PTSAkyep5UnTQfZUiscwMF4UZMNB4pgFL8tnLYX0iM90mMbUFZFhrCX7dsgqT5rdMvulMb/MC55AGrU6BDOoheOAho0xtr5gZtlkfsHBS+FPIlY1NvPse8/4srzt34fMQef9GZYkZDs4xDUvO7dnoBnuiTMGErLdoSn6Qp8C9Q2v0CB4V6w9Tv2Ox8gKhyB5QYXBptprAvUiZ3hRCkNKaByd1GZXbtZNv4GPcsnMSlef4g4EK8ZgPicsXAi6Sxg+UG3mXlTIDZq0XqhJT8GBPoW0b0hLsgyyaGSD85SOf25z9JnrUZWp1iBM2Ydjp9Dd4RBwmC036BQOhjgVzYX5BH31YpIm4tjlTKWoAi2Pz2/F+L8NdqQR1bdDTb98uQzqFQtcf64alZz++KIFAWPaH0DCsGtskilx52Kr9TiTKeTim4IaHe/fpvwmNYX2kAzMQKDMuh5rU9iUUu4pKXipuJPKHgbi2bnGDLJ0Bt2YpAiRtz2Z9ZSdlNMiIHIRxH+PGD2jEMJpblWxIH432gJCX8rKvL7FelMBLWxNAzzsT1ox7q87SyXdLb/lI8xRwpJXcr9zzUoB8zY0UlJO/UkwrWC5RjB18UfDkbUEwHRrckwAGY=
env:
  global:
  - secure: Q1mSLt3zyKNalkQQh1WYFawVbkY5atqkTkGj4cvcHMFhww2lG0l5KyCqf2J0Gb1ui0SRSxVsXtBFVtsYZe9eAKomtaoTzM9iHlaFWij92kCSt+siCAkVLgu12YaOSOOGTShNuU27axOOdnjpdlIY0rCaAmZgT/GQF1eVwaSbOIOtLdAlzqLT0s4pyYlvH7FJQy49ezhAiIxSLHp9MkkQs0PH7yOtPG3dLyCeqh3v0almWBeEzQZDw0fkMvSp4ENJeHnGUVRlqetkHO/Ivzh9jGGOoGrK5mIfyFAbFyYGxlvuLQVpzY3yP8fRLVNnSgrWJJesUqYEcGUG9HlgVPwAXmDR6pqbox2eT6VrUS7PhEdf8DoJdzZxiWkbjMDHnYXu7rTCItu/uvXzsuYM0/y8VwbFAnNzW/hGXVgYlQiKPdmHf9nFEIuP9eEi59juqRtP9aCaU8SCRtRJkLVl1AfeUqxVyJZuE0lB4sqPxU+H/N3lHAYx21bTpIWo0rlU4Uv3elTmv3XZz3xp5iJpfpja/5U7SegJxffiN62+hLg1oEtm9wkT4JV085sA1PZKNt0F2tkylocF3XpjXzglbLagNlevJpxsJ1TSZmgQEELfuPMAVMppR/g4WJWcneFUomov0U9Z6kh3+WDbOBZ8tAwU8pVyAJEy+s7J57BcGH/WVEY=
  - secure: XrjC3C4L6DWVa9qLmV1Q5yYrfyRPpWlsBrluyRKeYgV4KmzB1iYLdHHXEfAdSx7nyhWX5xrBloEmrbABklGorz17axu8WNtaFqwzhLwzFaRdGH51EhEG1vn8Hy//ANus/d1962skHWA9UsM2rQaHRZd4IOq3Fjro3xemhUK5bWiBCgpTo7Jw1Q1TgW4FbM9rg4fvG3oIaS+sD+2qrZdCiljouZS6/RBg/HqXIoQV2zcdeM/dnBNP+wf24S93kVeCFMh4stbVR1T3mQU89Zytf92L2/edJWD9gF6OnXGL+RdnTvB8k9y6/tERHiyLpp57qHX/dhE0pzZqQ309CgHKTXVuvsqXAG3j7Zwyfb2nA0M78+4AUTzaQaKn9m7qRpZ/2y7pLBG+a3NnVg/Vg/UMPVBOFAS9PTbQz+GsF5+0XiwG7/pZhSxMzRGqLMSu70C1J9tBT7MSmzwgGyLUHFvwOrLwU17HGS4VdHtrmZJ5f5OsGdSuwqYp+RSWURjr3w88IdEd1YDyPBS14cnwGsuEwsYxA2/67lZen9drVpui4d/Jqz4qZ57JGmVxYEPbheDUwoxDfOKlFZfCjh6XCrJrOTStH/npQBQCBJ5DmRFoLE6lWZIcG/d7ryLxypyx5xz8LD8lz29dyTCmDxprYf+jjcvj/vBVDKPjqD5+34KHxDg=
